title: "Hippolyte Asah"
author: "Blog Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "..."
date_format: "%B %d, %Y"

# Add a search button to the navbar
post_search: true

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: "home" }
  - {file: "categories.html", title: "Categories", icon: "bars" }
  - {file: "README.md", title: "About me", icon: "user"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hfasah@hotmail.com"}
  - {title: Github, icon: github, url: "https://hfasah.github.io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
